version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: yarn
      - run: yarn build
  test:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - run: yarn
      - run:
          command : yarn test
          no_output_timeout : 30m
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
