version: "3.5"

services:
  build:
    build:
      context: ../
      dockerfile: Dockerfile.onbuild
    container_name: earth-build
    volumes:
      - ../public:/pub

  web:
    image: nginx
    ports:
      - 80:80
    container_name: earth-web
    restart: unless-stopped
    volumes:
      - ../public:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  pub:
