services:
  dura-earth-build:
    container_name: 'dura-earth-build'
    image: 'dura-earth-build'
    build:
        context: ../
    volumes:
      - public:/usr/src/app/public

  dura-earth-web:
    image: nginx
    ports:
      - 80:80
    container_name: 'dura-earth-web'
    restart: unless-stopped
    volumes:
      - public:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  public:
