services:
  earth-dev:
    ports:
      - 8000:8000
    build:
      context: ../
      dockerfile: Dockerfile.dev
    container_name: "earth-dev"
    volumes:
      - ../src:/usr/src/app/src
      - ../public:/usr/src/app/pub
